name: Publish iOS Release

on:
  push:
    branches:
      - feature/ci
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  publish_ios_release:
    name: Build & Publish iOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build & Publish iOS Release
        uses: spaccesi/flutter-ci-suite@main
        with:
          build-platforms: "ios"
          publish-destinations: "ios-app-store"
          ios-distribution-certificate-base64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_BASE64 }}
          ios-distribution-certificate-password: ${{ secrets.IOS_DISTISTRIBUTION_CERTIFICATE_PASSWORD }}
          ios-provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          apple-api-key-id: ${{ secrets.APPLE_API_KEY_ID }}
          apple-api-key-issuer-id: ${{ secrets.APPLE_API_KEY_ISSUER }}
          apple-api-key-content: ${{ secrets.APPLE_API_KEY_CONTENT }}
          ios-export-options-plist: "ios/Runner/ExportOptions.plist"